export default [
  {
    Titulo: "Alarme",
    TempoConj: "1 minuto (ritual)",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "8 horas",
    Escola: "Abjuração",
    Classes: "Mago/Guardião",
    Descricao:
      "Você coloca um alarme para intrusos desavisados. Escolha uma porta, uma janela ou uma área dentro do alcance que não seja maior que 6 metros cúbicos. Até a magia acabar, um alarme alerta você sempre que uma criatura Miúda ou maior tocarem ou entrarem na área protegida. Quando você conjura a magia, você pode designar as criaturas que não ativarão o alarme. Você também escolhe se o alarme será mental ou audível.\n\nUm alarme mental alerta você com um silvo na sua mente, se você estiver a até de 1,5 quilômetro da área protegida. Esse silvo acordará você se você estiver dormindo.\n\nUm alarme audível produz o som de um sino de mão por 10 minutos num raio de 18 metros.",
    Material: "um pequeno sino e um pequeno fio de prata.",
  },
  {
    Titulo: "Amizade Animal",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "24 horas",
    Escola: "Encantamento",
    Classes: "Bardo/Druida/Guardião",
    Descricao:
      "Essa magia deixa você convencer uma besta que você não quer prejudicar. Escolha uma besta que você possa ver dentro do alcance. Ela deve ver e ouvir você. Se a Inteligência da besta for 4 ou maior, a magia falha. Do contrário, a besta deve ser bem sucedida num teste de resistência de Sabedoria ou ficará enfeitiçada por você pela duração da magia. Se você ou um dos seus companheiros ferir o alvo, a magia termina.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma besta adicional para cada nível do espaço acima do 1°.",
    Material: "um punhado de comida.",
  },
  {
    Titulo: "Área Escorregadia",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "1 minuto",
    Escola: "Conjuração",
    Classes: "Mago",
    Descricao:
      "Graxa escorregadia cobre o solo em um quadrado de 3 metros centrado em um ponto, dentro do alcance, tornando essa área em terreno difícil pela duração.\n\nQuando a graxa aparece, cada criatura de pé na área deve ser bem sucedida num teste de resistência de Destreza ou cairá no chão. Uma criatura que entre na área ou termine seu turno nela, deve ser bem sucedido num teste de resistência de Destreza ou cairá no chão.",
    Material: "um pouco de pele de porco ou manteiga.",
  },
  {
    Titulo: "Armadura Arcana",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "8 horas",
    Escola: "Abjuração",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Você toca uma criatura voluntária que não esteja vestindo armadura e uma energia mágica protetora a envolve até a magia acabar. A CA base do alvo se torna 13 + o modificador de Destreza dele. A magia acaba se o alvo colocar uma armadura ou se você dissipa-la usando uma ação.",
    Material: "um pedaço de couro curado",
  },
  {
    Titulo: "Armadura de Agathys",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Abjuração",
    Classes: "Bruxa",
    Descricao:
      "Uma força magica protetora envolve você, manifestandose como um frio espectral que cobre você e seu equipamento. Você ganha 5 pontos de vida temporários pela duração. Se uma criatura atingir você com um ataque corpo-a-corpo enquanto estiver com esses pontos de vida, a criatura sofrerá 5 de dano de frio.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, tanto os pontos de vida temporários quanto o dano de frio aumentam em 5 para cada nível do espaço acima do 1°.",
    Material: "um copo de água.",
  },
  {
    Titulo: "Auxílio Divino",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Paladina",
    Descricao:
      "Sua oração fortalece você com radiação divina. Até o fim da magia, seus ataques com arma causam 1d4 de dano radiante extra ao atingirem.",
    Material: ".",
  },
  {
    Titulo: "Bênção",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Encantamento",
    Classes: "Clériga/Paladina",
    Descricao:
      "Você abençoa até três criaturas, à sua escolha, dentro do alcance. Sempre que um alvo realizar uma jogada de ataque ou teste de resistência antes da magia acabar, o alvo pode jogar um d4 e adicionar o valor jogado ao ataque ou teste de resistência.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.",
    Material: "um borrifo de água benta.",
  },
  {
    Titulo: "Bom Fruto",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Transmutação",
    Classes: "Druida",
    Descricao:
      "Até dez frutos aparecem na sua mão e são infundidos com magia pela duração. Uma criatura pode usar sua ação para comer um fruto. Comer um fruto restaura 1 ponto de vida e um fruto produz nutrientes suficientes para sustentar uma criatura por um dia.\n\nOs frutos perdem seu potencial se não forem consumidos dentro de 24 horas da conjuração dessa magia.",
    Material: "um raminho de visco.",
  },
  {
    Titulo: "Braços de Hadar",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Conjuração",
    Classes: "Bruxa",
    Descricao:
      "Você invoca o poder de Hadar, o Faminto Sombrio. Tentáculos de energia negra brotam de você e golpeiam todas as criaturas a até 3 metros de você. Cada criatura na área deve realizar um teste de resistência de Força. Se falhar, o alvo sofre 2d6 de dano necrótico e não pode fazer reações até o próximo turno dela. Em um sucesso, uma criatura sofre metade do dano e não sofre qualquer outro efeito.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.\n\nAlcance: raio de 3 mestros.",
    Material: ".",
  },
  {
    Titulo: "Bruxaria",
    TempoConj: "1 ação bônus",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1 hora",
    Escola: "Encantamento",
    Classes: "Bruxa",
    Descricao:
      "Você coloca uma maldição em uma criatura que você possa ver, dentro do alcance. Até a magia acabar, você causa 1d6 de dano necrótico extra no alvo sempre que atingi-lo com um ataque. Além disso, escolha uma habilidade quando você conjurar a magia. O alvo tem desvantagem em testes de habilidade feitos com a habilidade escolhida.\n\nSe o alvo cair a 0 pontos de vida antes da magia acabar, você pode usar uma ação bônus, no seu turno subsequente para amaldiçoar outra criatura.\n\nUma magia remover maldição conjurada no alvo acaba com a magia prematuramente.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 3° ou 4° nível, você poderá manter sua concentração na magia por até 8 horas. Quando você usar um espaço de magia de 5° nível ou superior, você poderá manter sua concentração na magia por até 24 horas.",
    Material: "o olho petrificado de um tritão.",
  },
  {
    Titulo: "Comando",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V",
    Duracao: "1 rodada",
    Escola: "Encantamento",
    Classes: "Clériga/Paladina",
    Descricao:
      "Você pronuncia uma palavra de comando para uma criatura que você possa ver dentro do alcance. O alvo deve ser bem sucedido num teste de resistência de Sabedoria ou seguirá seu comando no próximo turno dele. A magia não tem efeito se o alvo for um morto-vivo, se ele não entender seu idioma ou se o comando for diretamente nocivo a ele.\n\nAlguns comandos típicos e seus efeitos a seguir. Você pode proferir um comando diferente dos descritos aqui. Se o fizer, o Mestre descreve como o alvo reage. Se o alvo não puder cumprir o comando, a magia termina.\n\nAproxime-se. O alvo se move para próximo de você o máximo que puder na rota mais direta, terminando seu turno, se ele se mover a até 1,5 metro de você.\n\nLargue. O alvo larga o que quer que ele esteja segurando, e termina seu turno.\n\nFuja. O alvo gasta seu turno se movendo para longe de você da forma mais rápida que puder.\n\nDeite-se. O alvo deita-se no chão e então, termina seu turno.\n\nParado. O alvo não se move e não realiza nenhuma ação. Uma criatura voadora continua no alto, considerando que ela seja capaz de fazê-lo. Se ela tiver que se mover para continuar no alto, ela voa a mínima distância necessária para permanecer no ar.\n\nEm Níveis Superiores. Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°. As criaturas devem estar a 9 metros entre si para serem afetadas.",
    Material: ".",
  },
  {
    Titulo: "Compreender Idiomas",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Adivinhação",
    Classes: "Bardo/Bruxa/Feiticeira/Mago",
    Descricao:
      "Pela duração, você compreende o significado literal de qualquer idioma falado que você ouvir. Você também compreende qualquer idioma escrito que vir, mas você deve tocar a superfície onde as palavras estão escritas. Leva, aproximadamente, 1 minuto para ler uma página de texto.\n\nEssa magia não decifra mensagens secretas em textos ou glifos, como um selo arcano, que não seja parte de um idioma escrito.",
    Material: "uma pitada de fuligem e sal",
  },
  {
    Titulo: "Constrição",
    TempoConj: "1 ação",
    Alcance: "27 metros",
    Componentes: "V, S",
    Duracao: "Concentração, até 1min",
    Escola: "Conjuração",
    Classes: "Druida",
    Descricao:
      "Ervas e vinhas poderosas brotam do solo num quadrado de 6 metros a partir de um ponto dentro do alcance. Pela duração, essas plantas transformam o solo na área em terreno difícil.\n\nUma criatura na área quando você conjurar a magia deve ser bem sucedida num teste de resistência de Força ou ficará impedida pelo emaranhado de plantas, até a magia acabar. Uma criatura impedida pelas plantas pode usar sua ação para realizar um teste de Força, contra a CD da magia. Se for bem sucedido, irá se libertar.\n\nQuando a magia termina, as plantas conjuradas murcharão.",
    Material: ".",
  },
  {
    Titulo: "Convocar Familiar",
    TempoConj: "1 hora (ritual)",
    Alcance: "3 metros",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Conjuração",
    Classes: "Mago",
    Descricao:
      "Você adquire os serviços de uma familiar, um espírito que toma a forma de um animal, à sua escolha: aranha, caranguejo, cavalo marinho, coruja, corvo, doninha, gato, falcão, lagarto, morcego, peixe (arenque), polvo, rato, rã (sapo) ou serpente venenosa. Aparecendo em um espaço desocupado dentro do alcance, o familiar tem as mesmas estatísticas da forma escolhida, no entanto, ele é um celestial, corruptor ou fada (à sua escolha) ao invés de uma besta.\n\nSeu familiar até independentemente de você, mas ele sempre obedece aos seus comandos. Em combate, ele rola sua a própria iniciativa e age no seu próprio turno. Um familiar não pode atacar, mas ele pode realizar outras ações, como de costume.\n\nQuando um familiar cai a 0 pontos de vida, ele desaparece, não deixando qualquer corpo físico para trás. Ele reaparece depois de você conjurar essa magia novamente.\n\nEnquanto seu familiar estiver a até 30 metros de você, você pode se comunicar telepaticamente com ele. Além disso, com uma ação, você pode ver através dos olhos do familiar e ouvir através dos ouvidos dele, até o início do seu próximo turno, adquirindo os benefícios de qualquer sentido especial que o familiar possua. Durante esse período, você estará cego e surdo em relação aos seus próprios sentidos.\n\nCom uma ação, você pode, temporariamente, dispensar seu familiar. Ele desaparece dentro de uma bolsa dimensional onde ele aguarda sua convocação. Alternativamente, você pode dispensa-lo para sempre. Com uma ação, enquanto ele estiver temporariamente dispensado, você pode fazê-lo reaparecer em qualquer espaço desocupado a até 9 metros de você.\n\nVocê não pode ter mais de um familiar por vez. Se você conjurar essa magia enquanto já tiver um familiar, ao invés disso, você faz seu familiar existente adotar uma nova forma. Escolha uma das formas da lista acima. Seu familiar se transforma na criatura escolhida.\n\nFinalmente, quando você conjura uma magia com alcance de toque, seu familiar pode transmitir a magia, como se ele tivesse conjurado ela. Seu familiar precisa estar a até 30 metros de você e deve usar a reação dele para transmitir a magia quando você a conjurar. Se a magia necessitar de uma jogada de ataque, você usa seu modificador de ataque para essa jogada.",
    Material:
      "carvão, incenso e ervas no valor de 10 po, que devem ser consumidos pelo fogo em um braseiro de bronze.",
  },
  {
    Titulo: "Criar ou Destruir Água",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Transmutação",
    Classes: "Clériga/Druida",
    Descricao:
      "Você pode tanto criar quanto destruir água.\n\nCriar Água. Você cria 30 litros de água limpa dentro do alcance, em um recipiente aberto. Alternativamente, a água pode cair como chuva em um cubo de 9 metros dentro do alcance, extinguindo chamas expostas na área.\n\nDestruir Água. Você destrói até 30 litros de água de um recipiente aberto dentro do alcance. Alternativamente, você pode destruir um nevoeiro em um cubo de 9 metros dentro do alcance.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode criar ou destruir 30 litros de água adicionais, ou o tamanho do cubo aumenta em 1,5 metro, para cada nível do espaço acima do 1°.",
    Material:
      "uma gota de água se estiver criando ou alguns grãos de areia se estiver destruindo.",
  },
  {
    Titulo: "Curar Ferimentos",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Bardo/Clériga/Druida/Paladina/Guardião",
    Descricao:
      "Uma criatura que você tocar recupera uma quantidade de pontos de vida igual a 1d8 + seu modificador de habilidade de conjuração. Essa magia não produz efeito em mortos-vivos ou constructos.\n\nEm Níveis Superiores. Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, a cura aumenta em 1d8 para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Destruição Colérica",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Paladina",
    Descricao:
      "Da próxima vez que você atingir com um ataque corpo-acorpo com arma enquanto essa magia durar, seu ataque causará 1d6 de dano psíquico extra. Além disso, se o alvo for uma criatura, ele deve realizar um teste de resistência de Sabedoria ou ficará amedrontado por você até a magia acabar. Com uma ação, a criatura pode realizar um teste de resistência de Sabedoria contra a CD da magia para se manter resoluto e terminar a magia.",
    Material: ".",
  },
  {
    Titulo: "Destruição Lancinante",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Paladina",
    Descricao:
      "Da próxima vez que você atingir uma criatura com um ataque corpo-a-corpo com arma enquanto essa magia durar, sua arma flameja com intensas chamas brancas e o ataque causa 1d6 de dano de fogo extra ao alvo, fazendo-o incendiar pelas chamas. No início de cada turno dele, até a arma acabar, o alvo deve realizar um teste de resistência de Constituição. Se falhar na resistência, ele sofre 1d6 de dano de fogo. Se passar na resistência, a magia acaba. Se o alvo ou uma criatura a 1,5 metro dele usar uma ação para apagar as chamas ou se algum outro efeito extinguir as chamas (como submergir o alvo em água), a magia acaba.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano extra inicial causado por esse ataque aumenta em 1d6 para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Destruição Trovejante",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Paladina",
    Descricao:
      "Da primeira vez que você atingir um ataque corpo-a-corpo com arma enquanto essa magia durar, sua arma é rodeada por trovões que são audíveis a até 90 metros de você e o ataque causa 2d6 de dano trovejante extra no alvo. Além disso, se o alvo for uma criatura, ele deve ser bem sucedido num teste de resistência de Força ou será empurrado 3 metros para longe de você e cairá no chão.",
    Material: ".",
  },
  {
    Titulo: "Detectar Magia",
    TempoConj: "1 ação (ritual)",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Concentração, até 10min",
    Escola: "Adivinhação",
    Classes: "Bardo/Clériga/Druida/Feiticeira/Mago/Paladina/Guardião",
    Descricao:
      "Pela duração, você sente a presença de magia a até 9 metros de você. Se você sentir magia dessa forma, você pode usar sua ação para ver uma aura suave em volta de qualquer criatura ou objeto visível, na área que carrega magia, e você descobre a escolha de magia, se houver uma.\n\nA magia pode penetrar a maioria das barreiras, mas é bloqueada por 30 centímetros de rocha, 2,5 centímetros de metal comum, uma fina camada de chumbo, ou 90 centímetros de madeira ou terra.",
    Material: ".",
  },
  {
    Titulo: "Detectar o Bem e Mal",
    TempoConj: "1 ação (ritual)",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Concentração, até 10min",
    Escola: "Adivinhação",
    Classes: "Clériga/Paladina",
    Descricao:
      "Pela duração, você sabe se existe uma aberração, celestial, corruptor, elemental, fada ou morto-vivo, a até 9 metros de você, assim como onde a criatura está localizada. Similarmente, você sabe se existe um local ou objeto, a até 9 metros de você, que tenha sido consagrado ou profanado magicamente.\n\nA magia pode penetrar a maioria das barreiras, mas é bloqueada por 30 centímetros de rocha, 2,5 centímetros de metal comum, uma fina camada de chumbo, ou 90 centímetros de madeira ou terra.",
    Material: ".",
  },
  {
    Titulo: "Detectar Veneno e Doença",
    TempoConj: "1 ação (ritual)",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Adivinhação",
    Classes: "Clériga/Druida/Paladina/Guardião",
    Descricao:
      "Pela duração, você sente a presença e localização de venenos, criaturas venenosas e doenças a até 9 metros de você. Você também identifica o tipo de veneno, criatura venenosa ou doença em cada caso.\n\nA magia pode penetrar a maioria das barreiras, mas é bloqueada por 30 centímetros de rocha, 2,5 centímetros de metal comum, uma fina camada de chumbo, ou 90 centímetros de madeira ou terra",
    Material: "uma folha de teixo",
  },
  {
    Titulo: "Disco Flutuante de Tenser",
    TempoConj: "1 ação (ritual)",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Conjuração",
    Classes: "Mago",
    Descricao:
      "Essa magia cria um plano horizontal, circular de energia de 90 cm de diâmetro por 2,5 cm de espessura, que flutua 90 centímetros acima do chão em um espaço desocupado, à sua escolha, que você possa ver dentro do alcance. O disco permanece pela duração e pode suportar até 250 quilos. Se mais peso for colocado nele, a magia termina, e tudo em cima do disco cai no chão.\n\nO disco é imóvel enquanto você estiver a até 6 metros dele. Se você se afastar a mais de 6 metros dele, o disco seguirá você, mantendo-se a 6 metros de você. Ele pode atravessar terreno irregular, subir ou descer escadas, encostas e similares, mas ele não pode atravessar mudanças de elevação de 3 metros ou mais. Por exemplo, o disco não pode atravessar um fosso de 3 metros de profundidade nem poderia sair de tal fosso se tivesse sido criado no fundo dele.\n\nSe você se afastar mais de 30 metros do disco (tipicamente por ele não poder rodear um obstáculo para seguir você), a magia acaba.",
    Material: "uma gota de mercúrio",
  },
  {
    Titulo: "Disfarçar-se",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "1 hora",
    Escola: "Ilusão",
    Classes: "Bardo/Feiticeira/Mago",
    Descricao:
      "Você faz com que você mesmo – incluindo suas roupas, armadura, armas e outros pertences no seu personagem – pareça diferente até a magia acabar ou até você usar sua ação para dispensa-la. Você pode se parecer 30 centímetros mais baixo ou mais alto, e pode parecer magro, gordo ou entre ambos. Você não pode mudar o tipo do seu corpo, portanto, você deve adotar uma forma que tenha a mesma disposição básica de membros. No mais, a extensão da sua ilusão cabe a você.\n\nAs mudanças criadas por essa magia não conseguem se sustentar perante uma inspeção física. Por exemplo, se você usar essa magia para adicionar um chapéu ao seu visual, objetos que passarem pelo chapéu e qualquer um que tocá-lo não sentirá nada ou sentirá sua cabeça e cabelo. Se você usar essa magia para aparentar ser mais magro do que é, a mão de alguém que a erguer para tocar em você, irá esbarrar em você enquanto ainda está, aparentemente, está no ar.\n\nPara perceber que você está disfarçado, uma criatura pode usar a ação dela para inspecionar sua aparência e deve ser bem sucedida em um teste de Inteligência (Investigação) contra a CD da sua magia.",
    Material: ".",
  },
  {
    Titulo: "Duelo Compelido",
    TempoConj: "1 ação bônus",
    Alcance: "9 metros",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Encantamento",
    Classes: "Paladina",
    Descricao:
      "Você tenta compelir uma criatura a duelar com você. Uma criatura que você possa ver, dentro do alcance, deve realizar um teste de resistência de Sabedoria. Se falhar, a criatura é atraída por você, compelida pela sua exigência divina. Pela duração, ela tem desvantagem nas jogadas de ataque contra criaturas diferentes de você e deve realizar um teste de resistência de Sabedoria cada vez que tentar se mover para um espaço que esteja a mais de 9 metros de você; se ela passar no teste de resistência, essa magia não restringirá o movimento do alvo nesse turno.\n\nA magia termina se você atacar qualquer outra criatura, se você conjurar uma magia que afete uma criatura hostil diferente do alvo, se uma criatura amigável a você causar dano ou conjurar uma magia nociva nele ou se você terminar seu turno a mais de 9 metros do alvo.",
    Material: ".",
  },
  {
    Titulo: "Enfeitiçar Pessoa",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S",
    Duracao: "1 hora",
    Escola: "Encantamento",
    Classes: "Bruxa/Druida/Feiticeira/Mago",
    Descricao:
      "Você tenta enfeitiçar um humanoide que você possa ver dentro do alcance. Ele deve realizar um teste de resistência de Sabedoria, e recebe vantagem nesse teste se você ou seus companheiros estiverem lutando com ele. Se ele falhar, ficará enfeitiçado por você até a magia acabar ou até você ou seus companheiros fizerem qualquer coisa nociva contra ele. A criatura enfeitiçada reconhece você como um conhecido amigável. Quando a magia acabar, a criatura saberá que foi enfeitiçada por você.\n\nEm Níveis Superiores. Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°. As criaturas devem estar a até 9 metros umas das outras quando você for afeta-las",
    Material: ".",
  },
  {
    Titulo: "Escrita Ilusória",
    TempoConj: "1 minuto (ritual)",
    Alcance: "Toque",
    Componentes: "S, M",
    Duracao: "10 dias",
    Escola: "Ilusão",
    Classes: "Bruxa/Mago",
    Descricao:
      "Você escreve em um pergaminho, papel ou qualquer outro material adequado e tinge ele com uma poderosa ilusão que permanece pela duração.\n\nPara você e para qualquer criatura que você designar quando você conjura essa magia, a escrita parece normal, escrita com a sua caligrafia e transmite qualquer que seja a mensagem que você desejava quando escreveu o texto. Para todos os outros, a escrita aparece como se tivesse sido escrita com uma caligrafia desconhecida ou mágica que é inteligível. Alternativamente, você pode fazer a escrita parecer uma mensagem totalmente diferente, escrita com uma caligrafia e idioma diferentes, apesar de o idioma precisar ser um que você conheça.\n\nNo caso da magia ser dissipada, tanto a escrita original quanto a ilusória desaparecem.\n\nUma criatura com visão verdadeira pode ler a mensagem escondida.",
    Material:
      "uma tinta à base de chumbo valendo, no mínimo, 10 po, que é consumida pela magia.",
  },
  {
    Titulo: "Escudo Arcano",
    TempoConj: "1 reação",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "1 rodada",
    Escola: "Abjuração",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Uma barreira de energia invisível aparece e protege você. Até o início do seu próximo turno, você recebe +5 de bônus na CA, incluindo contra o ataque que desencadeou a magia, e você não sofre dano de mísseis mágicos.\n\nReação: que você faz quando é atingido por um ataque ou alvo da magia mísseis mágicos.",
    Material: ".",
  },
  {
    Titulo: "Escudo da Fé",
    TempoConj: "1 ação bônus",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Abjuração",
    Classes: "Clériga/Paladina",
    Descricao:
      "Um campo cintilante aparece ao redor de uma criatura, à sua escolha, dentro do alcance, concedendo +2 de bônus na CA pela duração.",
    Material: "um pequeno pergaminho com alguns textos sagrados escritos nele.",
  },
  {
    Titulo: "Falar com Animais",
    TempoConj: "1 ação (ritual)",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "10 minutos",
    Escola: "Adivinhação",
    Classes: "Bardo/Druida/Guardião",
    Descricao:
      "Você adquire a habilidade de compreender e se comunicar verbalmente com bestas, pela duração. O conhecimento e consciência de muitas bestas é limitado pela inteligência delas mas, no mínimo, as bestas poderão dar informações a você sobre os locais e monstros próximos, incluindo tudo que eles possam perceber ou tenham percebido no dia anterior. Você pode tentar persuadir uma besta a lhe prestar um favor, à critério do Mestre.",
    Material: ".",
  },
  {
    Titulo: "Fogo das Fadas",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Bardo/Druida",
    Descricao:
      "Cada objeto num cubo de 6 metros dentro do alcance fica delineado com luz azul, verde ou violeta (à sua escolha). Qualquer criatura na área, quando a magia é conjurada, também fica delineada com luz, se falhar num teste de resistência de Destreza. Pela duração, os objetos e criaturas afetadas emitem penumbra num raio de 3 metros.\n\nQualquer jogada de ataque contra uma criatura afetada ou objeto tem vantagem, se o atacante puder ver o alvo e, a criatura afetada ou objeto não recebe benefício por estar invisível.",
    Material: ".",
  },
  {
    Titulo: "Golpe Constritor",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Conjuração",
    Classes: "Guardião",
    Descricao:
      "Da próxima vez que você atingir uma criatura com um ataque com arma, antes do final da magia, um emaranhado maciço de vinhas espinhentas aparecem no local do impacto e o alvo deve ser bem sucedido num teste de resistência de Força ou ficará impedido pelas vinhas mágicas, até o fim da magia. Uma criatura Grande ou maior tem vantagem no seu teste de resistência. Se o alvo for bem sucedido na resistência, as vinhas murcharão.\n\nEnquanto estiver impedido pela magia, um alvo sofre 1d6 de dano perfurante no início de cada um dos turnos dele. Uma criatura impedida pelas vinhas ou uma que possa tocar a criatura, pode usar sua ação para realizar um teste de Força contra a CD da magia. Num sucesso, o alvo é libertado.\n\nEm Níveis Superiores. Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Heroísmo",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S",
    Duracao: "Concentração, até 1min",
    Escola: "Encantamento",
    Classes: "Bardo/Paladina",
    Descricao:
      "Uma criatura voluntária que você tocar é imbuída com bravura. Até a magia acabar, a criatura é imune a ser amedrontada e ganha pontos de vida temporários igual ao seu modificador de habilidade de conjuração, no início de cada turno dela. Quando a magia acabar, o alvo perde qualquer ponto de vida temporário restante dessa magia.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Identificação",
    TempoConj: "1 minuto (ritual)",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Adivinhação",
    Classes: "Bardo/Mago",
    Descricao:
      "Você escolhe um objeto que você deve tocar durante toda a conjuração da magia. Se ele for um item mágico ou algum outro objeto imbuído por magia, você descobre suas propriedades e como usá-lo, se exige sintonia para ser usado e quantas cargas ele tem, se aplicável. Você descobre se quaisquer magias estão afetando o item e quais eles são. Se o item foi criado por magia, você descobre que magia o criou.\n\nSe você, ao invés, tocar uma criatura durante toda a conjuração, você descobre quais magias, se houver alguma, estão afetando-a atualmente.",
    Material: "uma perola valendo, no mínimo, 100 po e uma pena de coruja",
  },
  {
    Titulo: "Imagem Silenciosa",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Ilusão",
    Classes: "Bardo/Feiticeira/Mago",
    Descricao:
      "Você cria a imagem de um objeto, criatura ou outro fenômeno visual que não tenha mais de 4,5 metros cúbicos. A imagem aparece num ponto, dentro do alcança, e permanece pela duração. A imagem é puramente visual; não é acompanhada por som, cheiro ou outros efeitos sensoriais.\n\nVocê pode usar sua ação para fazer a imagem se mover para qualquer ponto, dentro do alcance. À medida que a imagem muda de lugar, você pode alterar a aparência dela para que seu movimento pareça ser o natural para a imagem. Por exemplo, se você criar uma imagem de uma criatura e move-la, você pode alterar a imagem para que ela pareça estar andando.\n\nInteração física com a imagem, revelará que ela é uma ilusão, já que as coisas podem passar através dela. Uma criatura que usar sua ação para examinar a imagem, pode determinar que ela é uma ilusão com um teste de Inteligência (Investigação) bem sucedido contra a CD da magia. Se uma criatura discernir a ilusão como sendo isso, a criatura poderá ver através da imagem.",
    Material: "um pouco de lã",
  },
  {
    Titulo: "Inflingir Ferimentos",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Necromancia",
    Classes: "Clériga",
    Descricao:
      "Faça um ataque corpo-a-corpo com magia contra uma criatura dentro do alcance. Se atingir, o alvo sofre 3d10 de dano necrótico.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d10 para cada nível acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Leque Cromático",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "1 rodada",
    Escola: "Ilusão",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Um feixe ofuscante de luzes coloridas ordenadas, surge da sua mão. Role 6d10; o total é a quantidade de pontos de vida de criaturas que essa magia pode afetar. As criaturas num cone de 4,5 metros, originado de você, são afetadas em ordem ascendente dos seus pontos de vida (ignorando criaturas inconsciente e que não podem ver).\n\nComeçando com as criaturas que tiverem menos pontos de vida, cada criatura afetada por essa magia ficará cega até o fim da magia. Subtraia os pontos de vida de cada criatura do total antes de considerar os pontos de vida da próxima criatura. Os pontos de vida de uma criatura devem ser iguais ou menores que o total restante para que essa criatura seja afetada\n\nEm Níveis Superiores. Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, jogue 2d10 adicionais para cada nível do espaço acima do 1°.\n\nAlcance: cone de 4,5 metros.",
    Material: "um punhado de pó ou areia nas cores vermelha, amarela e azul",
  },
  {
    Titulo: "Mãos Flamejantes",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Enquanto você mantiver suas mãos com os polegares juntos e os dedos abertos, uma fino leque de chamas emerge das pontas dos seus dedos erguidos. Cada criatura num cone de 4,5 metros deve realizar um teste de resistência de Destreza. Uma criatura sofre 3d6 de dano de fogo se falhar no teste, ou metade desse dano se obtiver sucesso. \n\nO fogo incendeia qualquer objeto inflamável na área que não esteja sendo vestido ou carregado.\n\nEm Níveis Superiores. Se você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.\n\nAlcance: cone de 4,5 metros.",
    Material: ".",
  },
  {
    Titulo: "Marca do Caçador",
    TempoConj: "1 ação bônus",
    Alcance: "27 metros",
    Componentes: "V",
    Duracao: "Concentração, até 1 hora",
    Escola: "Adivinhação",
    Classes: "Guardião",
    Descricao:
      "Você escolhe uma criatura que possa ver, dentro do alcance e a marca misticamente como sua presa. Até a magia acabar, você causa 1d6 de dano extra ao alvo sempre que você o atingir com um ataque com arma e você tem vantagem em quaisquer testes de Sabedoria (Percepção) ou Sabedoria (Sobrevivência) feitos para encontrá-la. Se o alvo cair a 0 pontos de vida antes da magia acabar, você pode usar uma ação bônus, no seu turno subsequente para marcar uma nova criatura.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 3° ou 4° nível, você poderá manter sua concentração na magia por até 8 horas. Quando você usar um espaço de magia de 5° nível ou superior, você poderá manter sua concentração na magia por até 24 horas.",
    Material: ".",
  },
  {
    Titulo: "Mísseis Mágicos",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Você cria três dardos brilhantes de energia mística. Cada dardo atinge uma criatura, à sua escolha, que você possa ver, dentro do alcance. Um dardo causa 1d4 + 1 de dano de energia ao alvo. Todos os dardos atingem simultaneamente e você pode direciona-los para atingir uma criatura ou várias.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, a magia cria um dardo adicional para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Névoa Obscurecente",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S",
    Duracao: "Concentração, até 1 hora",
    Escola: "Conjuração",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Você cria uma esfera de 6 metros de raio de névoa, centrada num ponto, dentro do alcance. A esfera se espalha, dobrando esquinas, e a área dela é de escuridão densa. Ela permanece pela duração ou até um vento moderado ou mais rápido (pelo menos 15 quilômetros por hora) dispersa-la.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o raio da névoa aumenta em 6 metros para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Onda Trovejante",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Bardo/Druida/Feiticeira/Mago",
    Descricao:
      "Uma onda de força trovejante varre tudo a partir de você. Cada criatura num cubo de 4,5 metros originado em você, deve realizar um teste de resistência de Constituição. Se falhar na resistência, uma criatura sofrerá 2d8 de dano trovejante e será empurrada 3 metros para longe de você. Se obtive sucesso na resistência, a criatura sofrerá metade desse dano e não será empurrada.\n\nAlém disso, objetos soltos que estiverem completamente dentro da área de efeito serão automaticamente empurrados 3 metros para longe de você pelo efeito da magia e a magia emitirá um ressonante barulho de trovão audível a até 90 metros.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d8 para cada nível acima do 1°.\n\nAlcance: cubo de 4,5 metros.",
    Material: ".",
  },
  {
    Titulo: "Orbe Cromática",
    TempoConj: "1 ação",
    Alcance: "27 metros",
    Componentes: "V, S, M",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Você arremessa uma esfera de energia de 12 centímetros de diâmetro numa criatura que você possa ver dentro do alcance. Você escolhe ácido, frio, fogo, elétrico, veneno ou trovejante para o tipo de orbe que você cria e, então, realiza um ataque à distância com magia. Se o ataque atingir, a criatura sofre 3d8 de dano do tipo escolhido.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d8 para cada nível do espaço acima do 1°.",
    Material: "um diamante valendo, no mínimo, 50 po.",
  },
  {
    Titulo: "Queda Suave",
    TempoConj: "1 reação",
    Alcance: "18 metros",
    Componentes: "V, M",
    Duracao: "1 minuto",
    Escola: "Transmutação",
    Classes: "Bardo/Feiticeira/Mago",
    Descricao:
      "Escolha até cinco criaturas caindo, dentro do alcance. A taxa de descendência de uma criatura caindo é reduzida para 18 metros por rodada, até o fim da magia. Se a criatura aterrissar antes da magia acabar, ela não sofre nenhum dano de queda, pode aterrissar em pé e a magia termina para essa criatura.",
    Material: "uma pequena pena ou penugem similar.",
  },
  {
    Titulo: "Palavra Curativa",
    TempoConj: "1 ação bônus",
    Alcance: "18 metros",
    Componentes: "V",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Bardo/Clériga/Druida",
    Descricao:
      "Uma criatura, à sua escolha, que você possa ver dentro do alcance recupera uma quantidade de pontos de vida igual a 1d4 + seu modificador de habilidade de conjuração. Essa magia não tem efeito em mortos-vivos ou constructos.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, a cura aumenta em 1d4 para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Passos Longos",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Transmutação",
    Classes: "Bardo/Druida/Mago/Guardião",
    Descricao:
      "Você toca uma criatura. O deslocamento do alvo aumenta em 3 metros, até a magia acabar.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.",
    Material: "um pouco de barro",
  },
  {
    Titulo: "Perdição",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Encantamento",
    Classes: "Bardo/Clériga",
    Descricao:
      "Até três criaturas, à sua escolha, que você possa ver dentro do alcance, devem realizar um teste de resistência de Carisma. Sempre que um alvo que falhou nessa resistência realizar uma jogada de ataque ou um teste de resistência antes da magia acabar, o alvo deve rolar um d4 e subtrair o valor rolado da jogada de ataque ou teste de resistência.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você pode afetar uma criatura adicional para cada nível do espaço acima do 1°.",
    Material: "uma gota de sangue",
  },
  {
    Titulo: "Proteção contra o Bem e Mal",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 10min",
    Escola: "Abjuração",
    Classes: "Bruxa/Clériga/Mago/Paladina",
    Descricao:
      "Até a magia acabar, uma criatura voluntária que você tocar estará protegida contra certos tipos de criaturas: aberrações, celestiais, corruptores, elementais, fadas e mortos-vivos.\n\nA proteção garante diversos benefícios. As criaturas desse tipo tem desvantagem nas jogadas de ataque contra o alvo. O alvo não pode ser enfeitiçado, amedrontado ou possuído por elas. Se o alvo já estiver enfeitiçado, amedrontado ou possuído por uma dessas criaturas, o alvo terá vantagem em qualquer novo teste de resistência contra o efeito relevante.",
    Material: "água benta ou pó de prata e ferro, consumidos pela magia",
  },
  {
    Titulo: "Purificar Alimentos",
    TempoConj: "1 ação",
    Alcance: "3 metros",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Transmutação",
    Classes: "Clériga/Druida/Paladina",
    Descricao:
      "Toda comida e bebida não-mágica dentro de uma esfera de 1,5 metro de raio centrada num ponto, à sua escolha, dentro do alcance é purificada e se livrada de venenos ou doenças.",
    Material: ".",
  },
  {
    Titulo: "Raio Adoecente",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Necromancia",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Um raio adoecente de energia esverdeada chicoteia na direção de uma criatura dentro do alcance. Faça um ataque à distância com magia contra o alvo. Se atingir, o alvo sofrerá 2d8 de dano de veneno e deve realizar um teste de resistência de Constituição. Se falhar na resistência, ele também ficará envenenado até o final do seu próximo turno.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano da magia aumenta em 1d8 para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Raio de Bruxa",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Evocação",
    Classes: "Bruxa/Feiticeira/Mago",
    Descricao:
      "Um raio crepitante de energia azul é arremessado em uma criatura dentro do alcance, formando um arco elétrico contínuo entre você e o alvo. Faça um ataque à distância com magia contra a criatura. Se atingir, o alvo sofrerá 1d12 de dano elétrico e, em cada um dos seus turnos, pela duração, você pode usar sua ação para causar 1d12 de dano elétrico ao alvo, automaticamente. A magia acaba se você usar sua ação para fazer qualquer outra coisa. A magia também acaba se o alvo estiver fora do alcance da magia ou se você tiver cobertura total para ele.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano inicial aumenta em 1d12 para cada nível do espaço acima do 1°.",
    Material: "um galho de uma árvore que tenha sido atingida por um relâmpago",
  },
  {
    Titulo: "Raio Guiador",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S",
    Duracao: "1 rodada",
    Escola: "Evocação",
    Classes: "Clériga",
    Descricao:
      "Um lampejo de luz se lança em direção de uma criatura, à sua escolha, dentro do alcance. Realize um ataque à distância com magia contra o alvo. Se atingir, o alvo sofre 4d6 de dano radiante e, a próxima jogada de ataque contra esse alvo, antes do final do seu próximo turno, terá vantagem, graças a penumbra mística cintilando no alvo, até então.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Recuo Acelerado",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V, S",
    Duracao: "Concentração, até 10min",
    Escola: "Transmutação",
    Classes: "Bruxa/Feiticeira/Mago",
    Descricao:
      "Essa magia permite que você se mova a um ritmo incrível. Quando você conjura essa magia e, a partir de então, com uma ação bônus em cada um dos seus turnos, até a magia acabar, você pode realizar a ação de Disparada.",
    Material: ".",
  },
  {
    Titulo: "Repreensão Infernal",
    TempoConj: "1 reação",
    Alcance: "18 metros",
    Componentes: "V, S",
    Duracao: "Instantânea",
    Escola: "Evocação",
    Classes: "Bruxa",
    Descricao:
      "Você aponta seu dedo e a criatura que causou dano a você é, momentaneamente, envolta por chamas infernais. A criatura deve realizar um teste de resistência de Destreza. Ela sofre 2d10 de dano de fogo se falhar na resistência ou metade desse dano se obtiver sucesso.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d10 para cada nível do espaço acima do 1°.\n\nReação: que você faz em resposta ao sofre dano de uma criatura a até 18 metros de você e que você possa ver.",
    Material: "",
  },
  {
    Titulo: "Riso Histérico de Tasha",
    TempoConj: "1 ação",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "Concentração, até 1min",
    Escola: "Encantamento",
    Classes: "Bardo/Mago",
    Descricao:
      "Uma criatura, à sua escolha, que você possa ver, dentro do alcance, acha tudo hilariantemente engraçado e cai na gargalhada, se essa magia afeta-la. O alvo deve ser bem sucedido em um teste de resistência de Sabedoria ou cairá no chão, ficando incapacitado e incapaz de se levantar pela duração. Uma criatura com valor de Inteligência 4 ou inferior não é afetada.\n\nAo final de cada um dos turnos dela e, toda vez que sofrer dano, o alvo pode realizar outro teste de resistência de Sabedoria. O alvo terá vantagem no teste de resistência se ele for garantido por ele ter sofrido dano. Se obtiver sucesso, a magia acaba.",
    Material: "pequenas tortas e uma pena que é balançada no ar",
  },
  {
    Titulo: "Salto",
    TempoConj: "1 ação",
    Alcance: "Toque",
    Componentes: "V, S, M",
    Duracao: "1 minuto",
    Escola: "Transmutação",
    Classes: "Druida/Feiticeira/Mago/Guardião",
    Descricao:
      "Você toca uma criatura. A distância de salto da criatura é triplicada até a magia acabar.",
    Material: "uma perna de gafanhoto",
  },
  {
    Titulo: "Santuário",
    TempoConj: "1 ação bônus",
    Alcance: "9 metros",
    Componentes: "V, S, M",
    Duracao: "1 minuto",
    Escola: "Abjuração",
    Classes: "Clériga",
    Descricao:
      "Você protege uma criatura, dentro do alcance, contra ataques. Até a magia acabar, qualquer criatura que tentar atacar ou usar magias que causem dano contra criatura protegida deve, primeiro, realizar um teste de resistência de Sabedoria. Se falhar na resistência, a criatura deve escolher um novo alvo ou perderá o ataque ou magia. Essa magia não protege a criatura contra efeitos de área, como a explosão de uma bola de fogo.\n\nSe a criatura protegida realizar um ataque ou conjurar uma magia que afete uma criatura inimiga, essa magia acaba.",
    Material: "um pequeno espelho de prata",
  },
  {
    Titulo: "Saraivada de Espinhos",
    TempoConj: "1 ação bônus",
    Alcance: "Pessoal",
    Componentes: "V",
    Duracao: "Concentração, até 1min",
    Escola: "Conjuração",
    Classes: "Guardião",
    Descricao:
      "Da próxima vez que você atingir uma criatura com um ataque à distância com arma, antes da magia acabar, essa magia cria uma chuva de espinhos que brota da sua arma à distância ou munição. Além do efeito normal do ataque, o alvo do ataque e cada criatura a até 1,5 metro dele, devem realizar um teste de resistência de Destreza. Uma criatura sofre 1d10 de dano perfurante se falhar na resistência ou metade desse dano se obtiver sucesso.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d10 para cada nível do espaço acima do 1° (até o máximo de 6d10).",
    Material: "",
  },
  {
    Titulo: "Servo Invisível",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Conjuração",
    Classes: "Bardo/Bruxa/Mago",
    Descricao:
      "Essa magia cria uma força invisível, sem mente e sem forma que realiza tarefas simples, ao seu comando, até a magia acabar. O servo aparece do nada em um espaço desocupado no chão, dentro do alcance. Ele tem CA 10, 1 ponto de vida, Força 2 e não pode atacar. Se ele cair a 0 pontos de vida, a magia acaba.\n\nUma vez em cada um dos seus turnos, com uma ação bônus, você pode comandar, mentalmente, o servo para se mover até 4,5 metros e interagir com um objeto. O servo pode realizar tarefas simples que um serviçal humano faria, como buscar coisas, limpar, consertar, dobrar roupas, acender chamas, servir comida ou derramar vinho. Uma vez que um comando seja dado, o servo realiza a tarefa da melhor forma possível, até completar a tarefa, então esperará o seu próximo comando.\n\nSe você comandar o servo a realizar uma tarefa que poderia afasta-lo a mais de 18 metros de você, a magia termina.",
    Material: "um pedaço de barbante e um pouco de madeira",
  },
  {
    Titulo: "Sono",
    TempoConj: "1 ação",
    Alcance: "36 metros",
    Componentes: "V, S, M",
    Duracao: "1 minuto",
    Escola: "Encantamento",
    Classes: "Bardo/Feiticeira/Mago",
    Descricao:
      "Essa magia põem as criaturas num entorpecimento mágico. Jogue 5d8; o total é a quantidade de pontos de vida de criaturas afetados pela magia. As criaturas numa área de 6 metros de raio, centrada no ponto escolhido, dentro do alcance, são afetadas em ordem ascendente dos pontos de vida atuais delas (ignorando criaturas inconscientes).\n\nComeçando com as criaturas com menos pontos de vida atuais, cada criatura afetada por essa magia cai inconsciente até a magia acabar, sofrer dano ou alguém usar sua ação para sacudi-la ou esbofeteá-la até acordar.\n\nSubtraia os pontos de vida de cada criatura do total antes de seguir para a próxima criatura com menos pontos de vida atuais. Os pontos de vida atuais da criatura devem ser iguais ou menores que o valor restante para que a criatura possa ser afetada.\n\nMortos-vivos e criaturas imunes a serem enfeitiçadas não são afetadas por essa magia.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2º nível ou superior, jogue 2d8 adicionais para cada nível do espaço acima do 1°.",
    Material: "um punhado de areia fina, pétalas de rosas ou um grilo",
  },
  {
    Titulo: "Sussurros Dissonantes",
    TempoConj: "1 ação",
    Alcance: "18 metros",
    Componentes: "V",
    Duracao: "Instantânea",
    Escola: "Encantamento",
    Classes: "Bardo",
    Descricao:
      "Você sussurra uma melodia dissonante que apenas uma criatura, à sua escolha, dentro do alcance pode ouvir, causando-lhe uma terrível dor. O alvo deve realizar um teste de resistência de Sabedoria. Se falhar na resistência, ele sofrerá 3d6 de dano psíquico e deve, imediatamente, usar sua reação, se disponível, para se mover para o mais longe possível de você. A criatura não se moverá para um terreno obviamente perigoso, como uma fogueira ou abismo. Se obtiver sucesso na resistência, o alvo sofre metade do dano e não precisa se afastar de você. Uma criatura surda obtém sucesso automaticamente na sua resistência.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, o dano aumenta em 1d6 para cada nível do espaço acima do 1°.",
    Material: ".",
  },
  {
    Titulo: "Vitalidade Falsa",
    TempoConj: "1 ação",
    Alcance: "Pessoal",
    Componentes: "V, S, M",
    Duracao: "1 hora",
    Escola: "Necromancia",
    Classes: "Feiticeira/Mago",
    Descricao:
      "Reforçando-se com uma vitalidade necromântica ilusória, você ganha 1d4 + 4 pontos de vida temporários pela duração.\n\nEm Níveis Superiores. Quando você conjurar essa magia usando um espaço de magia de 2° nível ou superior, você ganha 5 pontos de vida temporários adicionais para cada nível do espaço de magia acima do 1°.",
    Material: "uma pequena quantidade de álcool ou bebidas destiladas",
  },
];
